language: node_js
node_js:
- '10'
services: docker
branches:
  except: "/^[0-9]/"
env:
  global:
  - TZ='Europe/Oslo'
  - RELEASE_VERSION="$(git fetch --unshallow || true && git rev-list --count $TRAVIS_COMMIT)"
  - DOCKER_IMAGE_FULL_NAME="$TRAVIS_REPO_SLUG:$RELEASE_VERSION"
  - GITHUB_APP_ID=26100
script:
- npm run test-coverage
- docker build -t "$DOCKER_IMAGE_FULL_NAME" .
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push
    "$DOCKER_IMAGE_FULL_NAME"
  on:
    branch: master
after_deploy:
- git remote add auth-origin "https://x-access-token:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
- git tag $RELEASE_VERSION
- git push auth-origin --tags
before_install:
- openssl aes-256-cbc -K $encrypted_98dcabe19c4b_key -iv $encrypted_98dcabe19c4b_iv
  -in travis/datajegerne-private-key.enc -out travis/datajegerne-private-key.pem -d
- export GH_TOKEN=$(./travis/generate-installation-token.sh `./travis/generate-jwt.sh ./travis/datajegerne-private-key.pem
  $GITHUB_APP_ID`)
