language: node_js
node_js:
- '10'
services: docker
branches:
  except: "/^[0-9]/"
env:
  global:
  - TZ='Europe/Oslo'
  - RELEASE_VERSION="$(git fetch --unshallow || true && git rev-list --count $TRAVIS_COMMIT)"
  - DOCKER_IMAGE_FULL_NAME="$TRAVIS_REPO_SLUG:$RELEASE_VERSION"
  - GITHUB_APP_ID=26100
  - DOCKER_USERNAME=naviktdocker
  - secure: c2MGKZv2BIiAH+khSpdkUdBBVPuhbRxfQ1gJ5W2EuehY7S/uhgyPQQca6TJnFXFEmnvA5kwvOgxoYAd1rv2xsPKwG0TaYRzEYm4cUaLglJrgRptXuaQgoS3uElY59SAZydbDARrEd4P8vSpaeUtgPO3zCPx12Fub4IAih11Ui+imwdoECTdHq/Opt1PsZGtcb61EVeP5nEYqzjdRfxh1xKiYMsHE/MAI7EcrbfknApjzL6XstVMqZoDfF7rH3l05bQwLV1eTDAEnuABuBuG2+R/duLJHQT31qr5DyF9ya+ZFZ/YdZzKI4aDPrPW3spf2MRGfFOIiCTdEQOOsPmWIY6F7JROY0OF0NbDw89pq5phxnSJxskqbXfYa4cRMUDLmyhyE3pi9GzPQEJ9DSOwZPpMVIdatFKeeRvPGT4ugKH1blNzywF2tCnECWt/DB5QGlXnnnz3vOAiKAbz+wQa92NTgGZdzShmrNQne6W8Jg/CT0rWpiD90p/NMwfVmh2+s2jYZ4IRGCgazRLp1uAfWM06aarGpA3EZ+Y1q44ju74kzgzbG7jH5sQpu8Y3dOK38kn/bC1S2Uy/B4pwnl0BYBlNGt2lsvBLnhTnuCG9+GDUw4aoqGeroKYEIf0VT5kHb1TS2p860btG/qLKrO4icwKyeKHe79RufJ02Ij2WpijI=
script:
- npm run build
- docker build -t "$DOCKER_IMAGE_FULL_NAME" .
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push
    "$DOCKER_IMAGE_FULL_NAME"
  on:
    branch: master
after_deploy:
- git remote add auth-origin "https://x-access-token:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
- git tag $RELEASE_VERSION
- git push auth-origin --tags
before_install:
- openssl aes-256-cbc -K $encrypted_98dcabe19c4b_key -iv $encrypted_98dcabe19c4b_iv
  -in travis/datajegerne-private-key.enc -out travis/datajegerne-private-key.pem -d
- export GH_TOKEN=$(./travis/generate-installation-token.sh `./travis/generate-jwt.sh
  ./travis/datajegerne-private-key.pem $GITHUB_APP_ID`)
