apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: data-catalog-frontend
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 80
  ingresses:
    - "https://datacatalog.nais.oera-q.local/datacatalog"
    - "https://www-q0.nav.no/datacatalog"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: datacatalog/index.html
    initialDelay: 60
  readiness:
    path: datacatalog/index.html
    initialDelay: 60
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      memory: 128Mi
  vault:
    enabled: true
