apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: data-catalog-frontend
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 80
  ingresses:
    - "https://datakatalog.prod-sbs.nais.io"
    - "https://datakatalog.nav.no"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: index.html
    initialDelay: 10
  readiness:
    path: index.html
    initialDelay: 10
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      memory: 128Mi
  vault:
    enabled: true
