version: 2.1
orbs:
  nais: navikt/nais-deployment@1.1.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    
    steps:
    - checkout
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
    - run:
        name: Node install
        command: npm install
    - run:
        name: Test application
        command: npm run test
    - run:
        name: Build application
        command: npm run build
    - save_cache:
        paths:
          - ~/usr/local/lib/node_modules # location depends on npm version
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - nais/docker-deploy:
        image: navikt/data-catalog-frontend
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: NAIS deployment
      - nais/deploy:
          name: Deploy preprod
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/data-catalog-frontend
          image: navikt/data-catalog-frontend
          github-app-id: 26100
          nais-template: naiserator-preprod.yaml
          environment: dev-sbs
          team: teamdatajegerne
          requires:
            - build
          filters:
            branches:
              only:
                - master
