version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  build:
    working_directory: ~/frontend_wf
    docker:
      - image: circleci/node:10
    steps:
    - checkout
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
    - run:
        name: Test application
        command: npm run test
    - save_cache:
        paths:
          - ~/usr/local/lib/node_modules # location depends on npm version
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
  deploy_to_staging:
    environment:
      - PROJECT_NAME: "datajegerne"
      - GOOGLE_PROJECT_ID: "datajegerne"
      - GOOGLE_COMPUTE_ZONE: "europe-north1-b"
      - GOOGLE_CLUSTER_NAME: "datajegerne-cluster"
    working_directory: ~/frontend_wf
    docker:
      - image: circleci/node:10
    steps:
    - setup_remote_docker
    - checkout
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
    - run:
        name: Node install
        command: npm install
    - run:
        name: Build application
        command: npm run build
    - save_cache:
        paths:
          - ~/usr/local/lib/node_modules # location depends on npm version
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run:
        name: apt update
        command: sudo apt-get update || sudo apt-get update
    - gcp-gcr/gcr-auth
    - gcp-gcr/build-image:
        image: navikt/data-catalog-frontend
        tag: $CIRCLE_BUILD_NUM
    - gcp-gcr/push-image:
        image: navikt/data-catalog-frontend
        tag: $CIRCLE_BUILD_NUM
    - gcp-gke/install
    - gcp-gke/init
# Timeout pga at clusteret er privat.
#    - gcp-gke/rollout-image:
#        cluster: datajegerne-cluster
#        deployment: data-catalog-backend
#        container: data-catalog-backend
#        image: gcr.io/datajegerne/navikt/$CIRCLE_PROJECT_REPONAME:$RELEASE_VERSION
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: datajegerne
          filters:
            branches:
              ignore: master
      - deploy_to_staging:
          filters:
            branches:
              only: master
          context: datajegerne